# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fae883ec003a4345c95c1cacf122f5af1b22d30664caa893bb4b71fce14bc8f29a8b9be5a56822f81794bbb8a7344a21a7e098d2c8032e38fc8402fb35c235c9

test:
  secret_key_base: a92416bc4e6f265516beddb77474c7f468bc02bcdec4b1666ce8b2b3e2ab439976c0c54b8a35bfe6caf792993fd7779bbf98dcb14d825b3d4c26c37bd1a06fa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
